default:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: ./dev.db
      schema: main
      schemas_and_paths:
        main: ./dev.db
      schema_directory: ./schemas